# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3ab8a7edce9f56a265810e5b0eab11bcae4f6d6c4595df46745abcf9d2df04bdc0a0b3d692d52b61172f40300bff8a8fa84aa847836ea6e33ed9cbaaaa8b6b29

test:
  secret_key_base: b9ac702f4762fc36168c08867924079f85a1f3416170c9ea6989b9ef785558e5272eb88e74ae557c9408ad2aec90c9c1776c7df2a50fe52b09b8425dfe78e9e4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
